run:
  concurrency: 4

  skip-files:
    - "aws-cost-notification/mock/mock_*\\.go"

linters:
  enable-all: true
  disable:
    - bodyclose
    - gochecknoglobals
    - gochecknoinits
    - goheader
    # - gomnd
    - interfacer
    - lll
    - maligned
    - scopelint
    - unparam
    - wrapcheck
    # - wsl

issues:
  exclude-use-default: true
  fix: true
