AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-cost-notification

  Sample SAM Template for aws-cost-notification

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  AwsCostNotificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["aws-cost-notification"]
      Role: !GetAtt AwsCostNotificationFunctionIamRole.Arn
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: "cron(0 0 * * ? *)"
            Name: CostNotificationSchedule
            Description: cost notification schedule
            Enabled: true
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SLACK_WEBHOOK_URL: VALUE
          SLACK_CHANNEL: VALUE
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./aws-cost-notification
      Dockerfile: Dockerfile
  AwsCostNotificationFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: "cost-notification-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ce:GetCostAndUsage"
                  - "ce:GetDimensionValues"
                  - "ce:GetReservationCoverage"
                  - "ce:GetReservationPurchaseRecommendation"
                  - "ce:GetReservationUtilization"
                  - "ce:GetTags"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

Outputs:
  AwsCostNotificationFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt AwsCostNotificationFunction.Arn
